#!/bin/bash

echo "=== Railway URL Finder ==="
echo ""
echo "To find your Railway app URL:"
echo ""
echo "Method 1: Railway Dashboard"
echo "1. Go to: https://railway.app"
echo "2. Sign in to your account"
echo "3. Click on 'NeuroLink-BCI' project"
echo "4. Look for the URL in the top section or Settings > Domains"
echo ""
echo "Method 2: Railway CLI (if installed)"
echo "railway status"
echo ""
echo "Method 3: Check Environment Variables"
echo "Railway automatically sets:"
echo "- RAILWAY_PUBLIC_DOMAIN"
echo "- RAILWAY_STATIC_URL"
echo ""
echo "Your URL should look like:"
echo "https://neurolink-bci-production.railway.app"
echo "or"
echo "https://neurolink-bci-production-xxxx.up.railway.app"
echo ""
echo "Once you find it, update Vercel environment variables:"
echo "REACT_APP_API_URL = https://your-railway-url.railway.app"
