[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PORT = "5000"
PYTHON_VERSION = "3.10"