name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-socketio flask-cors torch numpy scikit-learn pandas matplotlib

    - name: Install Node dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Test Python backend
      run: |
        python -c "import flask; print('Flask installed successfully')"

    - name: Deployment successful
      run: |
        echo "Build completed successfully!"
        echo "Frontend and backend are ready for deployment"